### ISSUE TITLE
When an icon is inserted at the beginning of the paragraph one can't delete it.

### ISSUE THREAD

**Issue by yerzhant** [brstuff/ckawesome#3]
How to reproduce: 
- go to http://io.blackdevelop.com/ckawesome/;
- insert an icon at the very beginning;
- place the cursor after of before the icon;
- press backspace or delete buttons.
http://joxi.ru/12MlLG4CVYaGmJ
One must say though, that when an icon is placed at the middle of the text, then it's ok.

**Comment by sebastiansulinski** [comment]
This is happening because plugin as it stands adds the empty span tag.

What you need to do is to update `ckawesome/dialogs/ckawesome.js` by adding `cka.appendHtml("&nbsp;");` somewhere before call to `editor.insertElement(cka);` i.e.

```javascript
cka.appendHtml("&nbsp;");

editor.insertElement(cka);
```

**Comment by brstuff** [comment]
Fixed with #6 .
Thanks Sebastian.

**Comment by yerzhant** [comment]
Thank you Sebastian and brstuff.
